// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTOn6OF0OpeJC5PgMDlWZG9JRi0vxSxo',
    appId: '1:590713649591:web:b74b07b5747b5e72ca1032',
    messagingSenderId: '590713649591',
    projectId: 'superdo-2c7b1',
    authDomain: 'superdo-2c7b1.firebaseapp.com',
    storageBucket: 'superdo-2c7b1.appspot.com',
    measurementId: 'G-L2QRYJR56X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwBZi0nhA7muagHnHw09GprA2ClvgRJs',
    appId: '1:590713649591:android:21de72dc12989376ca1032',
    messagingSenderId: '590713649591',
    projectId: 'superdo-2c7b1',
    storageBucket: 'superdo-2c7b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwwG4Ha0Cc_FgaAu1jHM8tZlGAo6k4x68',
    appId: '1:590713649591:ios:8e790d4b4ceaf2c2ca1032',
    messagingSenderId: '590713649591',
    projectId: 'superdo-2c7b1',
    storageBucket: 'superdo-2c7b1.appspot.com',
    iosClientId: '590713649591-jmktj2qc6ov1aot5852fb16d133i8i4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountantPro',
  );
}
