// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3A7laPhvsC_HkEbV9e9ytVXzFWoLoV64',
    appId: '1:662323600697:web:761865e828a99237e29ce8',
    messagingSenderId: '662323600697',
    projectId: 'accountant-p',
    authDomain: 'accountant-p.firebaseapp.com',
    storageBucket: 'accountant-p.appspot.com',
    measurementId: 'G-CLJ5TZR0EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFgmPGBgwWm02itU_lYlO1D3l5AmpCg4I',
    appId: '1:662323600697:android:97f455d0de45025ee29ce8',
    messagingSenderId: '662323600697',
    projectId: 'accountant-p',
    storageBucket: 'accountant-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WBPdwZoeIVN4N9uC1OSV1mYmL3j4928',
    appId: '1:662323600697:ios:001f82f6a2c3a48ce29ce8',
    messagingSenderId: '662323600697',
    projectId: 'accountant-p',
    storageBucket: 'accountant-p.appspot.com',
    iosClientId: '662323600697-q6r99sji7p95c10783q5gg8pf5mrhact.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountantPro',
  );
}
